#!/bin/bash
#############################################
# Cipi — SMTP / Email Notifications
# Optional: notify on errors (backup, deploy, cron, workers)
#############################################

[[ -z "${SMTP_CFG:-}" ]] && readonly SMTP_CFG="${CIPI_CONFIG}/smtp.json"
# System msmtprc ONLY — never /etc/cipi/.msmtprc (AppArmor/setgid cannot read it).
[[ -z "${SMTP_RC:-}" ]] && readonly SMTP_RC="/etc/msmtprc"
[[ -z "${SMTP_RC_LEGACY:-}" ]] && readonly SMTP_RC_LEGACY="${CIPI_CONFIG}/.msmtprc"

_smtp_is_enabled() {
    [[ -f "$SMTP_CFG" ]] && [[ "$(vault_read smtp.json | jq -r '.enabled // false')" == "true" ]]
}

_smtp_drop_setgid() {
    local bin; bin=$(command -v msmtp) || return 0
    if [[ -g "$bin" ]]; then
        chmod g-s "$bin" 2>/dev/null || true
    fi
}

_smtp_ensure_msmtp() {
    if ! command -v msmtp &>/dev/null; then
        step "Installing msmtp..."
        apt-get update -qq && apt-get install -y -qq msmtp msmtp-mta
        success "msmtp installed"
    fi
    _smtp_drop_setgid
    rm -f "$SMTP_RC_LEGACY" 2>/dev/null || true
}

_smtp_trust_file() {
    local f
    for f in /etc/ssl/certs/ca-certificates.crt /etc/pki/tls/certs/ca-bundle.crt; do
        [[ -f "$f" && -r "$f" ]] && { printf '%s' "$f"; return 0; }
    done
    return 1
}

_smtp_quote() {
    printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

# Write system /etc/msmtprc from vault. Required for send (AppArmor blocks
# passwordeval helpers like cat, and blocks reading /etc/cipi/*).
_smtp_write_rc() {
    [[ ! -f "$SMTP_CFG" ]] && return 1
    _smtp_drop_setgid
    rm -f "$SMTP_RC_LEGACY" 2>/dev/null || true

    local _sj host port user pass from tls starttls trust_file pass_q
    _sj=$(vault_read smtp.json) || return 1
    host=$(echo "$_sj" | jq -r '.host // ""')
    port=$(echo "$_sj" | jq -r '.port // 587')
    user=$(echo "$_sj" | jq -r '.user // ""')
    pass=$(echo "$_sj" | jq -r '.password // ""')
    from=$(echo "$_sj" | jq -r '.from // ""')
    local tls_raw; tls_raw=$(echo "$_sj" | jq -r '.tls // true')
    [[ "$tls_raw" == "true" ]] && tls="on" || tls="off"

    if [[ "$tls" != "on" ]]; then
        starttls="off"
    elif [[ "$port" == "465" ]]; then
        starttls="off"
    else
        starttls="on"
    fi

    [[ -z "$host" || -z "$user" || -z "$pass" ]] && return 1
    pass_q=$(_smtp_quote "$pass")
    trust_file=""; trust_file=$(_smtp_trust_file) || trust_file=""
    # No logfile: AppArmor often denies msmtp writing under /var/log/* (send still
    # works, but msmtp prints a scary Permission denied on the log path).

    umask 077
    {
        echo "# Generated by Cipi — do not edit; use: cipi smtp configure"
        echo "defaults"
        echo "auth           on"
        echo "tls            ${tls}"
        [[ -n "$trust_file" ]] && echo "tls_trust_file ${trust_file}"
        echo ""
        echo "account        cipi"
        echo "host           ${host}"
        echo "port           ${port}"
        echo "from           ${from}"
        echo "user           ${user}"
        echo "password       \"${pass_q}\""
        echo "tls_starttls   ${starttls}"
        echo ""
        echo "account default : cipi"
    } > "$SMTP_RC" || return 1

    # System config: no "user secrets" chmod-600 check. Group msmtp for setgid hosts.
    if getent group msmtp &>/dev/null; then
        chown root:msmtp "$SMTP_RC" 2>/dev/null || chown root:root "$SMTP_RC" 2>/dev/null || true
        chmod 640 "$SMTP_RC" || return 1
    else
        chown root:root "$SMTP_RC" 2>/dev/null || true
        chmod 600 "$SMTP_RC" || return 1
    fi
    return 0
}

_smtp_can_reach() {
    local host="$1" port="$2"
    [[ -n "$host" && -n "$port" ]] || return 1
    if command -v timeout &>/dev/null; then
        timeout 5 bash -c "echo >/dev/tcp/${host}/${port}" 2>/dev/null && return 0
    else
        bash -c "echo >/dev/tcp/${host}/${port}" 2>/dev/null && return 0
    fi
    if command -v nc &>/dev/null; then
        nc -z -w 5 "$host" "$port" 2>/dev/null && return 0
    fi
    return 1
}

_smtp_bool_flag() {
    local v="${1:-}"
    case "$(echo "$v" | tr '[:upper:]' '[:lower:]')" in
        1|true|on|yes) echo "on" ;;
        0|false|off|no) echo "off" ;;
        *) echo "" ;;
    esac
}

_smtp_save_config() {
    local host="$1" port="$2" user="$3" pass="$4" from="$5" to="$6" tls="$7" enabled="$8"
    jq -n \
        --arg h "$host" --arg p "$port" --arg u "$user" --arg s "$pass" \
        --arg f "$from" --arg t "$to" \
        --argjson tl "$([[ "$tls" == "on" ]] && echo true || echo false)" \
        --argjson e "$([[ "$enabled" == "on" ]] && echo true || echo false)" \
        '{host:$h,port:$p,user:$u,password:$s,from:$f,to:$t,tls:$tl,enabled:$e}' \
        | vault_write smtp.json
    _smtp_write_rc || { error "Failed to write /etc/msmtprc"; return 1; }
    return 0
}

_smtp_configure() {
    parse_args "$@"
    _smtp_ensure_msmtp
    local host="" port="587" user="" pass="" from="" to="" tls="on" enabled="on"

    if [[ -f "$SMTP_CFG" ]]; then
        local _sj; _sj=$(vault_read smtp.json)
        host=$(echo "$_sj" | jq -r '.host // ""')
        port=$(echo "$_sj" | jq -r '.port // "587"')
        user=$(echo "$_sj" | jq -r '.user // ""')
        pass=$(echo "$_sj" | jq -r '.password // ""')
        from=$(echo "$_sj" | jq -r '.from // ""')
        to=$(echo "$_sj" | jq -r '.to // ""')
        [[ "$(echo "$_sj" | jq -r '.tls // true')" == "true" ]] && tls="on" || tls="off"
        [[ "$(echo "$_sj" | jq -r '.enabled // true')" == "true" ]] && enabled="on" || enabled="off"
    fi

    # Non-interactive when any required flag is present (API / scripts).
    local noninteractive=false
    if [[ -n "${ARG_host:-}" || -n "${ARG_user:-}" || -n "${ARG_password:-}" || -n "${ARG_from:-}" || -n "${ARG_to:-}" ]]; then
        noninteractive=true
    fi

    if [[ "$noninteractive" == "true" ]]; then
        [[ -n "${ARG_host:-}" ]] && host="${ARG_host}"
        [[ -n "${ARG_port:-}" ]] && port="${ARG_port}"
        [[ -n "${ARG_user:-}" ]] && user="${ARG_user}"
        [[ -n "${ARG_password:-}" ]] && pass="${ARG_password}"
        [[ -n "${ARG_from:-}" ]] && from="${ARG_from}"
        [[ -n "${ARG_to:-}" ]] && to="${ARG_to}"
        if [[ -n "${ARG_tls:-}" ]]; then
            tls=$(_smtp_bool_flag "${ARG_tls}")
            [[ -z "$tls" ]] && { error "--tls must be on/off (or true/false)"; exit 1; }
        fi
        if [[ -n "${ARG_enabled:-}" ]]; then
            enabled=$(_smtp_bool_flag "${ARG_enabled}")
            [[ -z "$enabled" ]] && { error "--enabled must be on/off (or true/false)"; exit 1; }
        fi
        # Allow omitting --password when updating an existing config (keep current secret).
        [[ -z "$pass" && -f "$SMTP_CFG" ]] && pass=$(vault_read smtp.json | jq -r '.password // ""')
        [[ -z "$host" || -z "$user" || -z "$pass" || -z "$from" || -z "$to" ]] && {
            error "Usage: cipi smtp configure --host=H --port=587 --user=U --password=P --from=F --to=T [--tls=on|off] [--enabled=on|off] [--no-test]"
            echo "      --password may be omitted when updating an existing configuration"
            exit 1
        }
        [[ "$port" =~ ^[0-9]+$ ]] || { error "Invalid --port"; exit 1; }

        _smtp_save_config "$host" "$port" "$user" "$pass" "$from" "$to" "$tls" "$enabled" || exit 1
        log_action "SMTP CONFIGURED: host=$host port=$port to=$to enabled=$enabled"

        if [[ "${ARG_no_test:-}" == "true" ]]; then
            success "SMTP configured (test skipped)"
            return 0
        fi

        step "Testing SMTP..."
        if ! _smtp_can_reach "$host" "$port"; then
            warn "SMTP saved but ${host}:${port} is unreachable from this server."
            return 0
        fi
        local test_err="" test_rc=0
        set +e
        test_err=$(_smtp_send "Cipi SMTP test" "This is a test email from Cipi. Notifications are configured correctly." 2>&1)
        test_rc=$?
        set -e
        if [[ $test_rc -eq 0 ]]; then
            success "SMTP configured and test email sent to ${to}"
        else
            warn "SMTP saved but test send failed."
            [[ -n "$test_err" ]] && echo -e "${DIM}${test_err}${NC}"
        fi
        return 0
    fi

    echo -e "\n${BOLD}SMTP — Email notifications${NC}"
    echo -e "${DIM}Configure SMTP, then use ${CYAN}cipi notifications${NC}${DIM} to choose which events send email.${NC}\n"

    read_input "SMTP host (e.g. smtp.gmail.com)" "$host" host
    read_input "SMTP port" "${port}" port
    read_input "SMTP user" "$user" user
    read_input "SMTP password" "$pass" pass
    read_input "From address (e.g. noreply@yourdomain.com)" "$from" from
    read_input "Notification recipient (To)" "$to" to
    echo -e "  ${DIM}Use TLS? (recommended for port 587)${NC}"
    read_input "TLS (on/off)" "$tls" tls
    echo -e "  ${DIM}Enable notifications?${NC}"
    read_input "Enabled (on/off)" "$enabled" enabled

    _smtp_save_config "$host" "$port" "$user" "$pass" "$from" "$to" "$tls" "$enabled" || exit 1
    log_action "SMTP CONFIGURED: host=$host port=$port to=$to enabled=$enabled"

    step "Testing SMTP..."
    if ! _smtp_can_reach "$host" "$port"; then
        warn "SMTP saved but ${host}:${port} is unreachable from this server."
        warn "Check outbound firewall / cloud security group (TCP ${port})."
        return 0
    fi

    local test_err="" test_rc=0
    set +e
    test_err=$(_smtp_send "Cipi SMTP test" "This is a test email from Cipi. Notifications are configured correctly." 2>&1)
    test_rc=$?
    set -e
    if [[ $test_rc -eq 0 ]]; then
        success "SMTP configured and test email sent to ${to}"
    else
        warn "SMTP saved but test send failed."
        [[ -n "$test_err" ]] && echo -e "${DIM}${test_err}${NC}"
        warn "Check credentials, From address, and TLS settings."
    fi
}

# Send using system /etc/msmtprc only — no -C, no passwordeval (AppArmor denies
# both /etc/cipi/* and executing cat from msmtp's passwordeval).
_smtp_send() {
    local subject="$1" body="$2"
    [[ ! -f "$SMTP_CFG" ]] && return 1
    _smtp_is_enabled || return 1
    _smtp_write_rc || return 1

    local _sj to from bin
    _sj=$(vault_read smtp.json) || return 1
    to=$(echo "$_sj" | jq -r '.to // empty')
    from=$(echo "$_sj" | jq -r '.from // "noreply@localhost"')
    [[ -z "$to" ]] && return 1
    bin=$(command -v msmtp) || return 1

    # MSMTPRC=/dev/null → ignore ~/.msmtprc; system /etc/msmtprc still loads.
    printf "From: %s\nTo: %s\nSubject: %s\nMIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\n\n%b\n" \
        "$from" "$to" "$subject" "$body" | \
        env MSMTPRC=/dev/null "$bin" -- "$to"
}

_smtp_disable() {
    if [[ -f "$SMTP_CFG" ]]; then
        vault_read smtp.json | jq '.enabled = false' | vault_write smtp.json
        success "Email notifications disabled"
    else
        warn "SMTP not configured. Run: cipi smtp configure"
    fi
}

_smtp_enable() {
    if [[ -f "$SMTP_CFG" ]]; then
        vault_read smtp.json | jq '.enabled = true' | vault_write smtp.json
        success "Email notifications enabled"
    else
        error "SMTP not configured. Run: cipi smtp configure"
        exit 1
    fi
}

_smtp_delete() {
    parse_args "$@"
    if [[ "${ARG_force:-}" != "true" ]] && [[ -t 0 ]]; then
        confirm "Remove SMTP config and disable notifications?" || return
    elif [[ "${ARG_force:-}" != "true" ]] && [[ ! -t 0 ]]; then
        error "Pass --force to delete SMTP config without a TTY"
        exit 1
    fi
    rm -f "$SMTP_CFG" "$SMTP_RC" "$SMTP_RC_LEGACY"
    log_action "SMTP DELETED"
    success "SMTP config removed"
}

_smtp_status() {
    parse_args "$@"
    if [[ "${ARG_json:-}" == "true" ]]; then
        if [[ ! -f "$SMTP_CFG" ]]; then
            jq -n '{configured:false,enabled:false,host:null,port:null,user:null,from:null,to:null,tls:null}'
            return 0
        fi
        vault_read smtp.json | jq '{
            configured: true,
            enabled: (.enabled // false),
            host: (.host // null),
            port: ((.port // "587") | tostring),
            user: (.user // null),
            from: (.from // null),
            to: (.to // null),
            tls: (.tls // true)
        } | del(.password)'
        return 0
    fi

    echo -e "\n${BOLD}SMTP / Email Notifications${NC}"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    if [[ ! -f "$SMTP_CFG" ]]; then
        echo -e "  ${DIM}Not configured${NC}"
        echo -e "  Run ${CYAN}cipi smtp configure${NC} to enable email notifications"
        echo ""
        return
    fi

    local _sj; _sj=$(vault_read smtp.json)
    local enabled to host port tls
    enabled=$(echo "$_sj" | jq -r '.enabled // false')
    to=$(echo "$_sj" | jq -r '.to // ""')
    host=$(echo "$_sj" | jq -r '.host // ""')
    port=$(echo "$_sj" | jq -r '.port // ""')
    tls=$(echo "$_sj" | jq -r '.tls // true')

    if [[ "$enabled" == "true" ]]; then
        echo -e "  Status:    ${GREEN}enabled${NC}"
    else
        echo -e "  Status:    ${YELLOW}disabled${NC}"
    fi
    echo -e "  Recipient: ${CYAN}${to}${NC}"
    echo -e "  Host:      ${CYAN}${host}${NC}:${CYAN}${port}${NC}"
    echo -e "  TLS:       ${CYAN}${tls}${NC}"
    echo ""
}

_smtp_test() {
    if ! _smtp_is_enabled; then
        error "SMTP not configured or disabled. Run: cipi smtp configure"
        exit 1
    fi
    _smtp_ensure_msmtp
    step "Sending test email..."
    local err="" rc=0
    set +e
    err=$(_smtp_send "Cipi test $(date '+%Y-%m-%d %H:%M')" "Test notification from Cipi." 2>&1)
    rc=$?
    set -e
    if [[ $rc -eq 0 ]]; then
        success "Test email sent"
    else
        error "Failed to send."
        [[ -n "$err" ]] && echo -e "${DIM}${err}${NC}"
        error "Check: cipi smtp status"
        exit 1
    fi
}

cipi_notify() {
    local subject="$1" body="$2" trigger="${3:-}"
    [[ -z "$subject" || -z "$body" ]] && return 0
    local client_ip; client_ip=$(_get_client_ip 2>/dev/null || echo "n/a")
    local key_name; key_name=$(_get_session_key_name 2>/dev/null || echo "n/a")
    log_event "$subject"
    if [[ -n "$trigger" ]] && declare -f _notify_trigger_enabled &>/dev/null && ! _notify_trigger_enabled "$trigger"; then
        return 0
    fi
    body="${body}\n\n---\nPerformed by: ${client_ip}\nSSH Key: ${key_name}"
    _smtp_send "$subject" "$body" 2>/dev/null || true
}

smtp_command() {
    local sub="${1:-}"; shift || true
    case "$sub" in
        configure) _smtp_configure "$@" ;;
        disable)   _smtp_disable ;;
        enable)    _smtp_enable ;;
        delete)    _smtp_delete "$@" ;;
        status)    _smtp_status "$@" ;;
        test)      _smtp_test ;;
        *) error "Use: configure disable enable delete status test"; echo "      configure --host= --port= --user= --password= --from= --to= [--tls=on|off] [--enabled=on|off] [--no-test]"; echo "      status --json | delete --force"; exit 1 ;;
    esac
}
